# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'my_agent_pool'


stages:
 - stage: Build
   jobs:
    - job: Build
      steps:
      - task: Npm@1
        inputs:
          command: 'install'
      - script: echo hello from my agent
        displayName: 'NPM install'
 - stage: Build_AWS_interface
   jobs:
     - job: Build_Aws_serverless
       steps:
         - script: |
             npm install serverless-offline --save-dev
             sls offline
             sls dynamodb install
             sls dynamodb start --migrate
             sls invoke local --function seek --data "{\"body\":\"{\\\"itemID\\\": \\\"1\\\"}\"}"
             sls invoke local --function buy --data "{\"body\":\"{\\\"itemID\\\": \\\”1\\\”, \\\"itemCount\\\”: \\\"1\\\"}\”}” 
           displayName: 'NPM install'
 - stage: Deply_test
   steps:
     - script: |
         sls offline
         sls dynamodb start --migrate
         npm test -- test/buyer.test.js 
         npm test -- test/handler.test.js
         npm test -- test/seeker.test.js
     - script: echo running test
            
              
