# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


stages:
 - stage: Build_Image_os
   jobs:
    - job: Linux
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: echo hello from Linux
 - stage: Build_Agent
   jobs:
    - job: Build_Agent
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
 - stage: Build_Application
   jobs:
    - job: Build_Application
      steps:
        - script: |
            npm install
          displayName: 'NPM install'
 - stage: Build_AWS_interface
   jobs:
     - job: Build_Aws
       steps:
         - script: |
             sls offline
           displayName: 'NPM install'
