# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'my_agent_pool'


stages:
 - stage: Build
   jobs:
    - job: Build
      steps:
      - task: Npm@1
        inputs:
          command: 'install'
      - script: echo hello from my agent
        displayName: 'NPM install'
 - stage: Build_AWS_interface
   jobs:
     - job: Build_Aws_serverless
       steps:
         - script: |
             npm install serverless-offline --save-dev
             sls offline
             sls dynamodb install
             sls dynamodb start --migrate
           displayName: 'NPM install'
     - job: Deploy_dynamodb
       steps:
         - script: |
             serverless invoke local --function seek --data "{\"body\":\"{\\\"itemID\\\": \\\"1\\\"}\"}"
             serverless invoke local --function buy --data "{\"body\":\"{\\\"itemID\\\": \\\”1\\\”, \\\"itemCount\\\”: \\\"1\\\"}\”}” 
           displayName: 'serverless execution'
 - stage: Deply_test
   jobs:
      - job: Deploy_test
        steps:
        - script: |
           serverless
           npm test
        - script: echo running test
            
              
